// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'INSERT API KEY',
    appId: '1:123184086020:web:7990b45d71634977c18951',
    messagingSenderId: '123184086020',
    projectId: 'e-commerce-4ebf1',
    authDomain: 'e-commerce-4ebf1.firebaseapp.com',
    storageBucket: 'e-commerce-4ebf1.firebasestorage.app',
    measurementId: 'G-EVSK9H5HJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'INSERT API KEY',
    appId: '1:123184086020:android:8c88c5bbd9e1f453c18951',
    messagingSenderId: '123184086020',
    projectId: 'e-commerce-4ebf1',
    storageBucket: 'e-commerce-4ebf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'INSERT API KEY',
    appId: '1:123184086020:ios:88e9005f4a93bc9dc18951',
    messagingSenderId: '123184086020',
    projectId: 'e-commerce-4ebf1',
    storageBucket: 'e-commerce-4ebf1.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'INSERT API KEY',
    appId: '1:123184086020:ios:88e9005f4a93bc9dc18951',
    messagingSenderId: '123184086020',
    projectId: 'e-commerce-4ebf1',
    storageBucket: 'e-commerce-4ebf1.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'INSERT API KEY',
    appId: '1:123184086020:web:da69c0c61695871cc18951',
    messagingSenderId: '123184086020',
    projectId: 'e-commerce-4ebf1',
    authDomain: 'e-commerce-4ebf1.firebaseapp.com',
    storageBucket: 'e-commerce-4ebf1.firebasestorage.app',
    measurementId: 'G-S5C49KCPNM',
  );
}
